name: sample_flutter_app
description: "A sample mobile app using Flutter, with some features: pinterest grid, routes, push named routes with context, drawer, horizontal cards and consuming the Unsplash Rest API for non-mocked data and more."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
